# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: posts.boy
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Articles about computers, apps, games, modding and programming.
baseurl: "" # the subpath of your site, e.g. /blog
permalink: /:title
url: "https://posts.boy.sh" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: boyvanamstel 
github_username: boyvanamstel 
#microdotblog_username: boyvanamstel
#google_analytics: UA-7720147-29

show_content: true

pagination:
  enabled: true
  sort_reverse: true
  permalink: "/page/:num/"

# Build settings
markdown: kramdown

theme: minima
plugins:
  - jekyll-feed
  - octopress-minify-html
  - jekyll-sitemap
  - jekyll-paginate-v2
include:
  - _redirects

defaults:
  - scope:
      path: ""
    values:
      image: /assets/img/avatar.jpg

minima:
  social_links:
    twitter: boyvanamstel
    github: boyvanamstel
    rss: true
  date_format: "%-d %B %Y"
